version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:13
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - APP_USER=${APP_USER}
            - APP_USER_PASSWORD=${APP_USER_PASSWORD}
            - APP_DB=${APP_DB}
        expose:
            - "5432"
        networks:
            - app-network
        volumes:
            - ./db/scripts:/docker-entrypoint-initdb.d/
            - ./db/data:/var/lib/postgresql/data

    uwsgi:
        container_name: uwsgi-nginx
        restart: unless-stopped
        depends_on:
            - postgres
        build:
            context: ./balance/
        image: uwsgi-nginx
        ports:
            - 8000:8000
        networks:
            - app-network
        environment:
            - APP_DB_USER=${APP_USER}
            - APP_DB_PASS=${APP_USER_PASSWORD}
            - APP_DB=${APP_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - SECRET_KEY=${SECRET_KEY}

networks:
    app-network:
        driver: bridge
